### ISSUE TITLE
Add storage adapter for YAC

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-cache#12]
An extreme fast shared memory cache extension [YAC](http://pecl.php.net/package/yac).
It's still in beta and it's not sure if this extension ever reaches it's beta state as it doesn't have a locking mechanism which leads a possibility to retrieve wrong data.

However it seems like this extension is already very popular and alternatives like APCu are still in beta, too.

---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-cache/issues/41

**Comment by weierophinney** [comment]
Why ZF3 and not next feature release?


---

Originally posted by @Maks3w at https://github.com/zendframework/zend-cache/issues/41#issuecomment-153887708

**Comment by weierophinney** [comment]
It's because of time. But you are right, if someone else likes to implement I'm happy :)


---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-cache/issues/41#issuecomment-153986964

**Comment by boesing** [comment]
After spending some time here and as this was never requested by any other user, I'll close this.
If there is still interest for this cache adapter, feel free to ping me.
