### ISSUE TITLE
Adapter example in README.md is wrong

### ISSUE THREAD

**Issue by rarog** [laminas/laminas-cache#125]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.11.2

#### Summary

`laminas-cache-adapter-storage-memory` is mentioned in the example in README.md, but it should rather be `laminas-cache-storage-adapter-memory`.

#### Current behavior

Mention of `laminas-cache-adapter-storage-memory`.

#### Expected behavior

Mention of `laminas-cache-storage-adapter-memory`.

**Comment by froschdesign** [comment]
The same problem can be found in the documentation: https://docs.laminas.dev/laminas-cache/installation/#avoid-unused-cache-adapters-are-being-installed

@rarog
Good catch! 👍

**Comment by boesing** [comment]
Closed with #127
