### ISSUE TITLE
[ZF3] Split out resource factories / manager

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-cache#13]
One of the most confusion part of the current cache component is the usage of resource manager.
The resource managers are used to instantiate resources (like an instance of `Memcache/d`) and to share the same resources over different instances of the fitting interface. Sharing resource is required to not open a new resource (like a network connection) to the same thing only to be able to use different storage instances with different options (like namespace / TTL).

In my opinion the cache adapters should not contain so much complexity and I would like to remove this functionality and simply let inject the resources into the adapters if required.

**But where move this functionality to?**
- Should this be part of another component like zend-servicemanager?
- Should this be done completely by the user?

Related:
- zendframework/zf2#5787
- zendframework/zf2#6381
- zendframework/zf2#6584

@weierophinney @ezimuel @Maks3w @Ocramius Thoughts?

---

Originally posted by @ghost at https://github.com/zendframework/zend-cache/issues/24

**Comment by weierophinney** [comment]
I used to think that db module is a good choice. but db use a table gateway model to process with ORM, it's much more RDBMS oriented.
since NoSQL is widely used today, I think it's a better idea to have a new design on data persistence and data process. Something like POJO implements hydrator interface with annotation to define the data source  seems a good choice for me to unified persistence and cache operation. I suggest a data source manager module to do all this.


---

Originally posted by @snowwolf007cn at https://github.com/zendframework/zend-cache/issues/24#issuecomment-257241204

**Comment by boesing** [comment]
I understood what is requested here. I will try to keep this in mind for further development.

However, I am not quite sure if we really need this anymore.
As of PSR-16, the interface got *much* more simpler and thus, it is possible to provide a per-value TTL. This works great on redis as I am using it in several projects by myself.

So the scenario mentioned in https://github.com/zendframework/zendframework/issues/5787 wont apply anymore, as you can simply create a cache without a namespace, assemble the cache key and provide a TTL per value.

This will lead to something like:
```php
return array(
  'caches' => array(
    'CacheStorage' => array(
      'adapter' => array(
        'name' => 'redis',
        'options' => array(
          'server' => 'devredis',
          'ttl' => 0,
          'namespace' => '',
        ),
      ),
    ),
);
```

```php
$cache = StorageFactory::factory($config['caches']['CacheStorage']);
$simpleCache = new SimpleCacheDecorator($cache);
$simpleCache->set('merlinid#foo', 'bar');
$simpleCache->set('trends#foo', 'bar', 86400);
```

So there is already a solution, it just needs a little bit of refactoring the code behind this *and* let the instance know about its TTL. This could be done by e.g. using a constant somewhere.

Closing this as this wont change in the foreseeable future.
