### ISSUE TITLE
Return values of some `AbstractAdapter` methods do not reflect the annotated return type

### ISSUE THREAD

**Issue by ravcz** [laminas/laminas-cache#15]
### Bug Report
There is wrong return type in

zend-cache/src/Storage/Adapter/AbstractAdapter.php

    /**
     * Remove an item.
     *
     * @param  string $key
     * @return bool
     * @throws Exception\ExceptionInterface
     *
     * @triggers removeItem.pre(PreEvent)
     * @triggers removeItem.post(PostEvent)
     * @triggers removeItem.exception(ExceptionEvent)
     */
    public function removeItem($key)

#### Expected behavior

There should be **@return mixed**

There is calling internally
return $this->triggerPost(__FUNCTION__, $args, $result);

which is returnng mixed.

**Comment by boesing** [comment]
Fixed with #295
