### ISSUE TITLE
PSR-6 `CacheItemPoolDecorator` does not validate the maximum cache key length

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cache#156]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes

#### Summary

As per PSR-6, a minimum cache key length of 64 characters have to be supported by the underlying storage.
The maximum can vary and depends on the implementing library.

For PSR-16 there was already a bugfix which allowed cache keys longer than 64 characters but for the `CacheItemPoolDecorator`, there is no such validation.

**Comment by boesing** [comment]
Relates to #154

**Comment by froschdesign** [comment]
Is this problem solved with #158 and released with [2.12.2](https://github.com/laminas/laminas-cache/releases/tag/2.12.2)?

**Comment by boesing** [comment]
Oh I guess yes. It was fixed with v2.12.0 probably. Thanks for the ping 👍🏼

**Comment by boesing** [comment]
Ah no, this is `PSR-6` related. The changes were made to `PSR-16` which already had some kind of maximum key length validation but `PSR-6` haven't.
