### ISSUE TITLE
PHP 8.1.1 support

### ISSUE THREAD

**Issue by srakhmanchuk** [laminas/laminas-cache#191]
### Feature Request

Could you please support the latest PHP version - 8.1.1? Unable to install the component while running PHP 8.1.1

 ```
composer require laminas/laminas-cache

Problem 1
    - laminas/laminas-servicemanager 3.7.0 requires php ^7.3 || ~8.0.0 -> your php version (8.1.1) does not satisfy that requirement.
    - laminas/laminas-servicemanager[3.8.0, ..., 3.10.0] require psr/container ^1.0 -> found psr/container[1.0.0, 1.1.0, 1.1.1, 1.1.2] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laminas/laminas-cache[3.1.0, ..., 3.1.2] require laminas/laminas-servicemanager ^3.7 -> satisfiable by laminas/laminas-servicemanager[3.7.0, 3.8.0, 3.9.0, 3.10.0].
    - Root composer.json requires laminas/laminas-cache ^3.1 -> satisfiable by laminas/laminas-cache[3.1.0, 3.1.1, 3.1.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require laminas/laminas-cache:*" to figure out if any version is installable, or "composer require laminas/laminas-cache:^2.1" if you know which you need.
```

**Comment by Ocramius** [comment]
It should be installable as per:

https://github.com/laminas/laminas-cache/blob/070f1942d031abb8ce976e3cfdbd74a2674655c8/composer.json#L34

**Comment by Ocramius** [comment]
In fact, support was provided in `3.0.0`: https://github.com/laminas/laminas-cache/releases/tag/3.0.0

**Comment by rieschl** [comment]
it seems that laminas-servicemanager is the issue. do you require `psr/container ^2.0` in your `composer.json`? laminas-servicemanager needs `1 0`.

**Comment by srakhmanchuk** [comment]
Yes, I have `psr/container ^2` and cannot be downgraded because of `symfony/service-contracts v3.0.0` requirements. Can I use the cache component without the `laminas/laminas-servicemanager` component?

**Comment by Ocramius** [comment]
It's part of the dependency set. The reason why `psr/container:^2` still isn't compatible is https://github.com/laminas/laminas-servicemanager/pull/96

We haven't yet gotten to a point where we can be backward compatible, yet upgrade to `psr/container:^2` too :|

**Comment by srakhmanchuk** [comment]
Got it, thank you!
