### ISSUE TITLE
A cache storage implementation is required, while the CaptureCache pattern does not require one

### ISSUE THREAD

**Issue by holtkamp** [laminas/laminas-cache#192]
_Note: I am not sure whether this is a "bug", might be an "improvement" as well but that was not suggested by the issue reporting template..._

### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.1

#### Summary

Currently a cache storage implementation is required while the [Capture Cache pattern](https://docs.laminas.dev/laminas-cache/v3/pattern/capture-cache/) does not need one.

#### Current behavior

Currently a cache storage implementation is required:
https://github.com/laminas/laminas-cache/blob/070f1942d031abb8ce976e3cfdbd74a2674655c8/composer.json#L35

This requirement can be satisfied by installing one of the cache storage adapters.

This is a nice approach to enforce installation of a cache storage adapter 👍 .

However: the Capture Cache pattern _also_ works _without_ such a cache storage adapters: https://github.com/laminas/laminas-cache/blob/070f1942d031abb8ce976e3cfdbd74a2674655c8/src/Pattern/CaptureCache.php#L271

That is why I suggested to "suggest" installing the cache storage adapters in https://github.com/laminas/laminas-cache/pull/62 and leave it to the user to determine which cache storage adapter to install.

#### How to reproduce

Try to install only `laminas/laminas-cache` using: `composer require laminas/laminas-cache`, this will result in:

```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laminas/laminas-cache ^3.1 -> satisfiable by laminas/laminas-cache[3.1.0, 3.1.1, 3.1.2, 3.1.x-dev, 3.2.x-dev].
    - laminas/laminas-cache[3.1.0, 3.1.1, 3.1.2, 3.1.x-dev, 3.2.x-dev] require laminas/laminas-cache-storage-implementation 1.0 -> could not be found in any version, but the following packages provide it:
      - laminas/laminas-cache-storage-adapter-memory Laminas cache adapter for memory
      - doctrine/doctrine-module Laminas Module that provides Doctrine basic functionality required for ORM and ODM modules
      - laminas/laminas-cache-storage-adapter-filesystem Laminas cache adapter for filesystem
      - laminas/laminas-cache-storage-adapter-redis Laminas cache adapter for redis
      - laminas/laminas-cache-storage-adapter-memcached Laminas cache adapter for memcached
      - laminas/laminas-cache-storage-adapter-blackhole Laminas cache adapter for blackhole
      - laminas/laminas-cache-storage-adapter-apcu Laminas cache adapter for apcu
      - laminas/laminas-cache-storage-adapter-session Laminas cache adapter for session
      - laminas/laminas-cache-storage-adapter-ext-mongodb Laminas cache adapter for ext-mongodb
      - laminas/laminas-cache-storage-adapter-memcache Laminas cache adapter for memcache
      - laminas/laminas-cache-storage-adapter-zend-server Laminas cache adapter for zend-server
      - laminas/laminas-cache-storage-adapter-apc Laminas cache adapter
      - laminas/laminas-cache-storage-adapter-dba Laminas cache adapter for dba
      - laminas/laminas-cache-storage-adapter-mongodb Laminas cache adapter for mongodb
      - laminas/laminas-cache-storage-adapter-wincache Laminas cache adapter for wincache
      - laminas/laminas-cache-storage-adapter-xcache Laminas cache adapter for xcache
      - cytec/laminas-cache-predis Redis adapter for Laminas Framework 3 with tagging support
      Consider requiring one of these to satisfy the laminas/laminas-cache-storage-implementation requirement.
```

A way to circumvent it is to also have Composer install a cache storage adapter without actually using it.

#### Expected behavior

I would expect to be able to "only" install `laminas/laminas-cache` without having to install a cache storage adapter.

**Comment by Ocramius** [comment]
> I would expect to be able to "only" install `laminas/laminas-cache` without having to install a cache storage adapter.

This is part of the `laminas/laminas-cache` design: if you only depend on the `laminas/laminas-cache` API definition, then you would probably only require `laminas/laminas-cache-storage-adapter-memory` as `require-dev`.

**Comment by holtkamp** [comment]
https://github.com/laminas/laminas-cache/issues/192#issuecomment-1050707582, thanks for the swift and clear reply.

Indeed, that is also a way to deal with it 😉  => closing issue
