### ISSUE TITLE
Added `PluginAwareInterface` and marked `EventsCapableInterface` as deprecated

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-cache#2]
Since the `StorageFactory` only checks for the `EventsCapableInterface`, it would result in a `Call to undefined method WhateverStorage::hasPlugin`.

Therefore, I would like to introduce that `PluginAwareInterface` for ZF3 and until then, I would like to mark the `EventsCapableInterface` usage as deprecated and provide this backport request.

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/177

**Comment by weierophinney** [comment]
@boesing 
The target version is 2.9?

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-cache/pull/177#issuecomment-420912521

**Comment by weierophinney** [comment]
@froschdesign I'm not sure since I did not got into those release processes already. If thats a change for 2.8, I could change the target branch to `master`

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/177#issuecomment-420913816

**Comment by weierophinney** [comment]
No no, the develop branch is correct!

I looked at the code and thought that it is for version 3 and then I saw the deprecation info. A deprecation goes in the next minor release.

---

Originally posted by @froschdesign at https://github.com/zendframework/zend-cache/pull/177#issuecomment-420915767

**Comment by weierophinney** [comment]
I guess this PR is ready to merge now @froschdesign, would be great if you drop the `WIP` label. Thanks.

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/177#issuecomment-422050500

**Comment by weierophinney** [comment]
I really could need this PR in my latest project [boesing/zend-cache-redis-cluster](https://github.com/boesing/zend-cache-redis-cluster) as I want to work with that `PluginCapableInterface::getPluginRegistry` to determine search for the serializer plugin.

I guess anything is on hold until we have more news about laminas?

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/177#issuecomment-520350035

**Comment by boesing** [comment]
Closed with #21
