### ISSUE TITLE
psr/cache V3 and psr/simple-cache V3 compatibilities

### ISSUE THREAD

**Issue by mayottecummings-seedbox** [laminas/laminas-cache#253]
Hello,

Since the library is not compatible with psr/cache V2 or V3, it's impossible to upgrade a project using Symfony to the latest version (V6). Eventually, it could lead to problems with newest version of PHP.

Can we have a date or at least an expected one for the next update/version of laminas-cache ?

Best regards :)

**Comment by Ocramius** [comment]
Duplicate of #133
