### ISSUE TITLE
laminas-cache is still using Laminas\Cache\StorageFactory::factory() which no longer exists

### ISSUE THREAD

**Issue by corentin-larose** [laminas/laminas-cache#257]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 2.21.0

Laminas cache version: 3.10

#### Summary

Laminas\I18n\Translator\Translator::factory() calls Laminas\Cache\StorageFactory::factory() which no longer exists.

I understand that adding laminas/laminas-cache-storage-deprecated-factory to your composer will fix it.
Still, there is a BC break.

#### Previous behavior

Cache adapter was instantiated.

#### Current behavior

An excpetion is thrown:

Fatal error: Uncaught Error: Class "Laminas\Cache\StorageFactory" not found in /var/www/vendor/laminas/laminas-i18n/src/Translator/Translator.php:227
Stack trace:
#0 /var/www/vendor/laminas/laminas-i18n/src/Translator/TranslatorServiceFactory.php(26): Laminas\I18n\Translator\Translator::factory(Array)
#1 /var/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(620): Laminas\I18n\Translator\TranslatorServiceFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Laminas\\I18n\\Tr...', NULL)
#2 /var/www/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(242): Laminas\ServiceManager\ServiceManager->doCreate('Laminas\\I18n\\Tr...')
#
[.....]
#7 {main}
  thrown in /var/www/vendor/laminas/laminas-i18n/src/Translator/Translator.php on line 227

#### How to reproduce

Using a translator cache adapter in configuration:

'translator' => [
            'cache' => [
                'adapter' => [
                    'name' => Redis::class,
                ],
                ],
            ],

**Comment by froschdesign** [comment]
@corentin-larose 
Install the separate package [laminas-cache-storage-deprecated-factory](https://github.com/laminas/laminas-cache-storage-deprecated-factory) to get the legacy support for the factory.

**Comment by froschdesign** [comment]
The laminas-i18n documentation has been updated on this topic: https://docs.laminas.dev/laminas-i18n/translator/caching/

**Comment by corentin-larose** [comment]
As you can see in my issue, I am aware of this. Nonetheless, it still is a BC break to my understanding (major in version didn't change => code is supposed to work BC). Am I wrong?

**Comment by froschdesign** [comment]
Version 3 is a new major version.

**Comment by corentin-larose** [comment]
Erf, me => tired, moving back and forth between versions, I lost my track, removing the issue, sorry for noise...

**Comment by froschdesign** [comment]
No problem at all. (Positive side effect of your issue report: the laminas-i18n documentation has been updated. 😃 👍🏻 )
