### ISSUE TITLE
Incompatibility of laminas-cache and newer psr/cache versions 

### ISSUE THREAD

**Issue by smsalert-mobi** [laminas/laminas-cache#292]
#### Summary

Can't update roave/psr-container-doctrine because this requires cache 1 and doctrine requires cache 2 or 3, thus preventing upgrade to php 8.3 overall.

#### Current behavior

composer update
Loading composer repositories with package information                                                                                               Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laminas/laminas-cache ^3.12 -> satisfiable by laminas/laminas-cache[3.12.0, 3.12.1].
    - roave/psr-container-doctrine 4.1.0 requires psr/cache ^2.0.0 || ^3.0.0 -> satisfiable by psr/cache[2.0.0, 3.0.0].
    - You can only install one version of a package, so only one of these can be installed: psr/cache[1.0.1, 2.0.0, 3.0.0].
    - laminas/laminas-cache[3.12.0, ..., 3.12.1] require psr/cache ^1.0 -> satisfiable by psr/cache[1.0.0, 1.0.1].
    - Root composer.json requires roave/psr-container-doctrine ^4.1 -> satisfiable by roave/psr-container-doctrine[4.1.0].

**Comment by boesing** [comment]
there wont be support for newer psr/cache majors in v3 of laminas-cache.
There will be v4 of laminas-cache at some point in time which adds support for newer versions of psr/cache.
There are no ETAs and there is no current effort in finishing v4 milestone in the near future. 

Either replace laminas-cache with something which supports newer psr versions or replace roave doctrine with the doctrine laminas module https://github.com/doctrine/DoctrineORMModule

Thats what I can offer you for now.

**Comment by boesing** [comment]
Closing this issue as `laminas-cache` v4 does provide support for `psr/cache` and `psr/simple-cache` v2 & v3.
