### ISSUE TITLE
[3.0] Mark static factories as deprecated

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-cache#3]
As requested in #175

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/176

**Comment by weierophinney** [comment]
Need to add the new StorageFactory to the ServiceManager configuration. Reminder for myself.

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/176#issuecomment-419957662

**Comment by weierophinney** [comment]
Well, it looks like the `pcntl_fork` unit test for `Filesystem` fails in travis for PHP 7.2 lowest dependencies.
I am on PHP 7.2 locally and the unit tests wont fail. Any suggestions?

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/pull/176#issuecomment-420206547

**Comment by weierophinney** [comment]
Most likely unrelated to your changes

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-cache/pull/176#issuecomment-420227951

**Comment by boesing** [comment]
Done with #50, #118
