### ISSUE TITLE
[ZF3] Remove StorageFactory and PatternFactory

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-cache#4]
Hey there,

I would like to drop those abstract factories in favor of using the related `PluginManager`s directly.
Since #93 introduces external packages, it will get more and more difficult to attach plugins/storage adapters to the PluginManagers, if not retrieved by the projects `ContainerInterface`.

Imho, each external package should provide their own factories for their plugins/storage adapters and just inject these to the related `PluginManager` (e.g. by using delegators? Some feedback would be great).

The original idea of @marc-mabe was to use the `Module` object to add aliases and factories to the `PluginManager` but as of `zend-config-aggregator` or in projects without `zend-mvc`, this wont work anymore.

I would appreciate to get some feedback on this.
@weierophinney 

---

Originally posted by @boesing at https://github.com/zendframework/zend-cache/issues/175

**Comment by weierophinney** [comment]
The idea makes sense, but removal is a hard BC break - can you maybe send a PR with deprecations for the classes you are targeting?

---

Originally posted by @Ocramius at https://github.com/zendframework/zend-cache/issues/175#issuecomment-419797337

**Comment by boesing** [comment]
I'll mark these factories as deprecated in v3 and remove them in v4 as of #49 and #50 
In case of #49, there is a new factory which provides new service to create storage adapters in a convenient way.
