### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by boesing** [laminas/laminas-cache#42]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

To be prepared for the december release of PHP 8.0, this repository has some additional TODOs to be tested against the new major version.

In order to make this repository compatible, one has to follow these steps:

- [ ] Modify `composer.json` to provide support for PHP 8.0 by adding the constraint `~8.0.0`
- [ ] Modify `composer.json` to drop support for PHP less than 7.3
- [ ] Modify `composer.json` to implement phpunit 9.3 which supports PHP 7.3+
- [ ] Modify `.travis.yml` to ignore platform requirements when installing composer dependencies (simply add `--ignore-platform-reqs` to `COMPOSER_ARGS` env variable)
- [ ] Modify `.travis.yml` to add PHP 8.0 to the matrix (*NOTE*: Do not allow failures as PHP 8.0 has a feature freeze since 2020-08-04!)
- [ ] Modify source code in case there are incompatibilities with PHP 8.0

**Comment by holtkamp** [comment]
Does merging this PR justify tagging a new release, so it can be easily used when referenced using Composer?

**Comment by Ocramius** [comment]
@holtkamp depends on @boesing's vision of this package: this was targeted towards `3.0.0`, perhaps we want it also for `2.x`, and then we could tag there? 

`3.0.0` doesn't seem ready yet, according to milestone.

**Comment by boesing** [comment]
As discussed on [2020-11-02](https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2020-11-02-TSC-Minutes.md#cache-adapters), PHP 8 will only be supported for v3 of laminas-cache.

The reason behind this is, that there is no way to test this library for PHP 8.0 without having a huge change in the CI build because there are several adapters which are not available on PHP 8.0 (yet) or are abandoned years ago (and not even working for PHP 7.X and so on).

Thats one reason why we've splitted up the adapters into several packages. It is easy to provide proper testing in each of these adapter packages. Thats how I found out that most of the adapters we are proving are:

- untestable due to the fact that there is no build for windows (on travis)
- untestable due to the fact that the cache-backend is closed source and needs a paid subscription (such as zend-server)
- untestable due to the fact that they're not actively in development for years

However, if someone contributes proper PRs targeting the 2.11.x branch of this package aswell as creating PRs in all cache adapter packages, I'll probably merge them as laminas-cache v3 will still take some time. 

But as of now, we won't spend time on it.

**Comment by boesing** [comment]
Just a follow-up here. 
PHP 8.0 is supported as of `laminas-cache` v2.12.0.

Those adapters which support PHP 8 are released aswell.
If there are adapters blocking you from updating, you may want to read [this](https://github.com/laminas/laminas-cache/blob/e419f8b71b16a349b67a40fb35f921a54d0bbfe9/README.md#avoid-unused-cache-adapters-are-being-installed).

With v3.0.0 (no ETA yet), the adapters are not part of the dependency-set of this project anymore and thus, the `replace` stuff can be removed from the `composer.json`.

**Comment by Slamdunk** [comment]
Hi, the link in the last comment is dynamic and no more valid.
Here's the permalink:

https://github.com/laminas/laminas-cache/blob/e419f8b71b16a349b67a40fb35f921a54d0bbfe9/README.md#avoid-unused-cache-adapters-are-being-installed
