### ISSUE TITLE
Should a raw string be serialized in Redis when using the SimpleCacheDecorator?

### ISSUE THREAD

**Issue by jensdenies** [laminas/laminas-cache#65]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.0 (But possible in other versions too)

#### Summary

I'm trying to insert a raw JSON string into my cache but I'm experiencing this error:

`The storage adapter "Laminas\Cache\Storage\Adapter\Redis" requires a serializer plugin; please see https://docs.laminas.dev/laminas-cache/storage/plugin/#quick-start for details on how to attach the plugin to your adapter."`

This error is thrown in the `Laminas\Cache\Psr\SimpleCache\SimpleCacheDecorator` class which checks whether serialization is required or not. In my case I just want to insert a raw string which doesn't require any serialization. Is this expected behavior?

#### Current behavior

An error is thrown when sending a string to my cache. Please refer to the summary above.

#### How to reproduce

Send a string to a Redis cache decorated with the `SimpleCacheDecorator` without the serializer plugin enabled.

#### Expected behavior

I'm not really sure, but I think it should just insert the string in Redis?

**Comment by boesing** [comment]
@jensdenies Yes, this is intended.
The PSR-16 standard is quite clear on what types the cache backend has to support.

https://www.php-fig.org/psr/psr-16/#14-data

If you want to work around this, you can simply copy & paste the decorator into your project and remove the appropriate code which verifies the serialization support.

**Comment by jensdenies** [comment]
@boesing Thanks.
