### ISSUE TITLE
I got this error with cron job after few minutes

### ISSUE THREAD

**Issue by teleinformatique** [laminas/laminas-cache#73]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | ^2.8

#### Summary

Uncaught Exception Error: Class 'Laminas\Cache\Psr\SimpleCache\SimpleCacheException' not found in /var/www/html/glpi/vendor/laminas/laminas-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php at line 307

**Comment by boesing** [comment]
@teleinformatique Can you give us some more informations on this?
At least the version you are using would be a good starting point. Thats why we explicitly asking for it in the Issue template.

After this, `ls -l /var/www/html/glpi/vendor/laminas/laminas-cache/src/Psr/SimpleCache/` could help us aswell to see if the exception file is available on the filesystem.
Debugging the contents of `/var/www/html/glpi/vendor/composer/autoload/` might help aswell.

**Comment by teleinformatique** [comment]
Thanks @boesing 
I use the version "laminas/laminas-cache": "^2.8" 
It's the output
`ls -l /var/www/html/glpi/vendor/laminas/laminas-cache/src/Psr/SimpleCache/

-rw-rwsr-- 1 root www-data 12950 Dec 31  2019 SimpleCacheDecorator.php
-rw-rwsr-- 1 root www-data   488 Dec 31  2019 SimpleCacheException.php
-rw-rwsr-- 1 root www-data   549 Dec 31  2019 SimpleCacheInvalidArgumentException.php`

`ls /var/www/html/glpi/vendor/composer/autoload/

ls: cannot access '/var/www/html/glpi/vendor/composer/autoload/': No such file or directory`


Thanks again

**Comment by boesing** [comment]
@teleinformatique thanks for providing the information. It would be helpful to have `composer show laminas/laminas-cache` output but I think you are on `2.8.2`.

Could you try to update the package to v2.10? The version you are using is 2,5 years old and maybe the composer autoloading is just not 100% available. You could also try to just re-dump the autoloader with `composer dump-autoload -o`.
The `SimpleCacheException` is available within the filesystem and thus, it must be something with the composer autoloader (or you've migrated to laminas with the `--keep-locked-versions` which is not supported in case you are experiencing errors).

Laminas packages are strictly following semver and therefore updating them is quite easy.

----

So, you might want to try these ways:

```
$ composer dump-autoload -o
```

If that does not help, you could try to update `laminas/laminas-cache` to v2.10:
 
```
$ composer update laminas/laminas-cache
```

If you get an error during update, you could try to use:
```
$ composer update laminas/laminas-cache --with-dependencies
```

If none of these will work, please provide us the following outputs:

## PHP Version Informations
```
$ php -v
```

## Installed Composer Packages
```
$ composer show
```

## Laminas Migration Informations
So how did you migrate from zendframework to laminas? Did you use `--keep-locked-versions` with the migration command from [this](https://github.com/laminas/laminas-migration) package?

**Comment by teleinformatique** [comment]
@boesing  Thanks for your response it's helping.
After launching the command `composer dump-autoload -o`
I got now this output 
`PHP Warning:  fopen(/var/www/html/glpi/files/_cache/glpi_cache_db_9.5.3ecca7e3fcf0b33c1161388665603e7a4.json): failed to open stream: Too many open files in /var/www/html/glpi/inc/cache/simplecache.class.php on line 387`

Before the first error.

For the composer update command. I get this

`Dependency "psr/simple-cache" is also a root requirement, but is not explicitly allowed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package paragonie/sodium_compat (installed at v1.13.0, required as ^1.14) is satisfiable by paragonie/sodium_compat[v1.13.0] but these conflict with your requirements or minimum-stability.
   `


$ php -v

`PHP 8.0.3 (cli) (built: Mar  4 2021 20:45:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies`

$ composer show

`blueimp/jquery-file-upload           v10.29.0 File Upload widget for jQuery.
brick/math                           0.8.14   Arbitrary-precision arithmeti...
container-interop/container-interop  1.2.0    Promoting the interoperabilit...
elvanto/litemoji                     2.0.1    A PHP library simplifying the...
guzzlehttp/guzzle                    6.5.5    Guzzle is a PHP HTTP client l...
guzzlehttp/promises                  v1.3.1   Guzzle promises library
guzzlehttp/psr7                      1.6.1    PSR-7 message implementation ...
htmlawed/htmlawed                    1.2.5    Official htmLawed PHP library...
iamcal/lib_autolink                  v1.7     Adds anchors to urls in a text
laminas/laminas-cache                2.9.0    Caching implementation with a...
laminas/laminas-eventmanager         3.2.1    Trigger and listen to events ...
laminas/laminas-i18n                 2.10.3   Provide translations for your...
laminas/laminas-json                 3.1.2    provides convenience methods ...
laminas/laminas-loader               2.6.1    Autoloading and plugin loadin...
laminas/laminas-mail                 2.12.0   Provides generalized function...
laminas/laminas-mime                 2.7.4    Create and parse MIME message...
laminas/laminas-serializer           2.9.1    Serialize and deserialize PHP...
laminas/laminas-servicemanager       3.4.0    Factory-Driven Dependency Inj...
laminas/laminas-stdlib               3.2.1    SPL extensions, array utiliti...
laminas/laminas-validator            2.13.4   Validation classes for a wide...
laminas/laminas-zendframework-bridge 1.0.4    Alias legacy ZF class names t...
mexitek/phpcolors                    v0.4     A series of methods that let ...
michelf/php-markdown                 1.9.0    PHP Markdown
monolog/monolog                      2.1.0    Sends your logs to files, soc...
paragonie/sodium_compat              v1.13.0  Pure PHP implementation of li...
phpmailer/phpmailer                  v6.1.6   PHPMailer is a full-featured ...
psr/cache                            1.0.1    Common interface for caching ...
psr/container                        1.0.0    Common Container Interface (P...
psr/http-message                     1.0.1    Common interface for HTTP mes...
psr/log                              1.1.3    Common interface for logging ...
psr/simple-cache                     1.0.1    Common interfaces for simple ...
ralouphie/getallheaders              3.0.3    A polyfill for getallheaders.
ramsey/collection                    1.0.1    A PHP 7.2+ library for repres...
ramsey/uuid                          4.0.1    A PHP library for generating ...
rlanvin/php-rrule                    v2.2.0   Lightweight and fast recurren...
sabre/dav                            4.1.3    WebDAV Framework for PHP
sabre/event                          5.1.2    sabre/event is a library for ...
sabre/http                           5.1.1    The sabre/http library provid...
sabre/uri                            2.2.1    Functions for making sense ou...
sabre/vobject                        4.3.3    The VObject library for PHP a...
sabre/xml                            2.2.3    sabre/xml is an XML library t...
scssphp/scssphp                      1.1.0    scssphp is a compiler for SCS...
sebastian/diff                       3.0.2    Diff implementation
simplepie/simplepie                  1.5.6    A simple Atom/RSS parsing lib...
symfony/console                      v4.4.9   Symfony Console Component
symfony/polyfill-php73               v1.17.0  Symfony polyfill backporting ...
symfony/polyfill-php80               v1.17.0  Symfony polyfill backporting ...
symfony/service-contracts            v1.1.8   Generic abstractions related ...
tecnickcom/tcpdf                     6.3.5    TCPDF is a PHP class for gene...
true/punycode                        v2.1.1   A Bootstring encoding of Unic...
wapmorgan/unified-archive            1.0.0    UnifiedArchive - unified inte..`

So how did you migrate from zendframework to laminas? 

No. I use the framework GLPI  [https://github.com/glpi-project/glpi/](url)

**Comment by boesing** [comment]
Hey @teleinformatique,

sorry for the delay here.
Well, as far as I can see, the GLPI framework provides a `composer.lock` as well and thus you should just execute `composer install`.

You might want to create an issue in the related [component](https://github.com/glpi-project/glpi/ ) as I cannot reproduce your issue. There might be plenty of reasons why you are getting these errors and thus its not `laminas-cache` related but related to your system you are using with the GLPI framework. So please raise the awareness in that project so the maintainers can help you further with their integration.

Thanks!
