### ISSUE TITLE
Zend Data Cache: APC compatibility broken

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-cache#9]
The Zend Data Cache comes with a compatibility layer for APC but the APC adapter doesn't work with it:

```
curl -sS -v 'http://localhost/test-zend-cache.php'
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
> GET /test-zend-cache.php HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 17 Feb 2016 21:08:54 GMT
< Server: Apache/2.4.6 (CentOS) PHP/5.6.17
< X-Powered-By: PHP/5.6.15 ZendServer/8.5.2
< ZRay-ID: 0@3936@1455741553@0
< Set-Cookie: ZDEDebuggerPresent=php,phtml,php3; path=/
< Content-Length: 81
< Content-Type: text/html; charset=UTF-8
< 
.............E.......E..EE..E.E.E.....E......E.FF.F.FF......SEEE. 65 / 72 ( 90%)
```

I currently don't get the full result. Could be a segmentation fault somewhere but it's a bit more work as the Zend Data Cache doesn't run in CLI and this bug is not very impotent.

-> For now if you are using the Zend Data Cache than please use one of the ZendServer[Disk|Shm] adapters.

---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-cache/issues/78

**Comment by weierophinney** [comment]
It should be a bug in `apcu` or `acp_bc`. Minimum required versions for each PHP versions are corrected in tests included in #153 

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-cache/issues/78#issuecomment-382457177

**Comment by weierophinney** [comment]
@thomasvargiu this issue is not about apcu_bc, this is about the apc compatibly layer of the zend data cache (part of zend server)

---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-cache/issues/78#issuecomment-383004946

**Comment by weierophinney** [comment]
@marc-mabe Ok, I don't know Zend Data Cache, but I think it could be a problem of Zend Data Cache. What do you think? And it's a 2 years old issue.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-cache/issues/78#issuecomment-383024069

**Comment by weierophinney** [comment]
@thomasvargiu Needs to be checked with the current Zend Server version if the problem still persist.
If so it should either be fixed (FZ or Zend Server) or at least be documented -> to use the specialized ZendServer[Disk|Shm] adapters.

---

Originally posted by @marc-mabe at https://github.com/zendframework/zend-cache/issues/78#issuecomment-383132168

**Comment by boesing** [comment]
I will close this as with the next minor version, we will bump PHP minimum version to 7.3.
There is no working APC extension for PHP 7.0+ and thus the APC component will not be part of this project.


@Ocramius Just to make sure that I'm on the right track:
- TSC decided to bump PHP versions in minors
- PHP version 7.0+ does not have a working APC extension
- next minor thus can drop the APC class as it wont work either on PHP 7.0+
- next minor will have several satellites as per [TSC voting](https://github.com/laminas/technical-steering-committee/blob/master/meetings/minutes/2020-05-04-TSC-Minutes.md#laminas-cache)

Thats a BC break, isnt it? But it might be a problem we probably cannot solve?
